export const techStacks = [
  {
    name: "NextJS",
    backgroundHover: "hover:bg-blue-500",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-blue-400",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "React",
    backgroundHover: "hover:bg-blue-600",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-blue-500",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "Angular",
    backgroundHover: "hover:bg-red-600",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-red-500",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "VueJS",
    backgroundHover: "hover:bg-green-500",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-green-400",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "JavaScript",
    backgroundHover: "hover:bg-yellow-400",
    textHover: "hover:text-black",
    darkBackgroundHover: "dark:hover:bg-yellow-300",
    darkTextHover: "dark:hover:text-black",
  },
  {
    name: "TypeScript",
    backgroundHover: "hover:bg-blue-400",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-blue-300",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "TailwindCSS",
    backgroundHover: "hover:bg-teal-500",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-teal-400",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "NodeJS",
    backgroundHover: "hover:bg-green-600",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-green-500",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "ExpressJS",
    backgroundHover: "hover:bg-gray-600",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-gray-500",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "GraphQL",
    backgroundHover: "hover:bg-purple-500",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-purple-400",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "PostgreSQL",
    backgroundHover: "hover:bg-blue-800",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-blue-700",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "Scala",
    backgroundHover: "hover:bg-red-800",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-red-700",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "Apache Kafka",
    backgroundHover: "hover:bg-gray-800",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-gray-900",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "Apache Spark",
    backgroundHover: "hover:bg-orange-500",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-orange-400",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "Apache Airflow",
    backgroundHover: "hover:bg-sky-200",
    textHover: "hover:text-black",
    darkBackgroundHover: "dark:hover:bg-sky-100",
    darkTextHover: "dark:hover:text-black",
  },
  {
    name: "Java",
    backgroundHover: "hover:bg-red-500",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-red-400",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "Spring Boot",
    backgroundHover: "hover:bg-green-700",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-green-600",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "Python",
    backgroundHover: "hover:bg-yellow-500",
    textHover: "hover:text-black",
    darkBackgroundHover: "dark:hover:bg-yellow-400",
    darkTextHover: "dark:hover:text-black",
  },
  {
    name: "Django",
    backgroundHover: "hover:bg-green-800",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-green-700",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "FastAPI",
    backgroundHover: "hover:bg-blue-700",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-blue-600",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "Docker",
    backgroundHover: "hover:bg-blue-200",
    textHover: "hover:text-black",
    darkBackgroundHover: "dark:hover:bg-blue-100",
    darkTextHover: "dark:hover:text-black",
  },
  {
    name: "Kubernetes",
    backgroundHover: "hover:bg-blue-600",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-blue-500",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "Terraform",
    backgroundHover: "hover:bg-purple-600",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-purple-500",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "Google Cloud",
    backgroundHover: "hover:bg-blue-400",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-blue-300",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "BigQuery",
    backgroundHover: "hover:bg-blue-900",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-blue-800",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "Pandas",
    backgroundHover: "hover:bg-red-400",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-red-300",
    darkTextHover: "dark:hover:text-white",
  },
  {
    name: "Scrapy",
    backgroundHover: "hover:bg-yellow-800",
    textHover: "hover:text-white",
    darkBackgroundHover: "dark:hover:bg-yellow-700",
    darkTextHover: "dark:hover:text-white",
  },
];
